### ISSUE TITLE
React v18 support

### ISSUE THREAD

**Issue by pkulcsarnr** [tcampb/react-calendly#106]
Update the package to support React v18.

**Comment by jordanlambrecht** [comment]
Hmmm.. I'm still getting this on build:

```
warning " > react-calendly@2.2.3" has incorrect peer dependency "react@^15.0.0 \|\| ^16.0.0 \|\| ^17.0.0".
warning " > react-calendly@2.2.3" has incorrect peer dependency "react-dom@^15.0.0 \|\| ^16.0.0 \|\| ^17.0.0".
```

**Comment by tcampb** [comment]
@jordanlambrecht it looks like you're using an older version of `react-calendly` which does not have React v18 included in the peer dependencies list. Are you able to upgrade to the latest version (4.0.1)?
