### ISSUE TITLE
onEventScheduled stopped working in 3.0.1

### ISSUE THREAD

**Issue by jmorrice** [tcampb/react-calendly#108]
Hi there,

Thanks for the great library!

We recently upgraded to v3.0.1 and the onEventScheduled callback on the `CalendlyEventListener` stopped firing for us. Are we missing something or is this a bug?

**Comment by tcampb** [comment]
@jmorrice - could you provide a code example that you are using that re-creates the issue? I wasn't able to re-create the issue on the [storybook site](https://tcampb.github.io/react-calendly/?path=/story/components--calendlyeventlistener).

**Comment by tcampb** [comment]
@jmorrice - could you confirm that the iframe created by `react-calendly` has the `embed_domain` query parameter in the src url? 

This attribute is required to receive messages from the iframe; the InlineWidget component should add this by default as seen [here](https://github.com/tcampb/react-calendly/blob/master/src/calendly.tsx#L145-L149).

**Comment by jmorrice** [comment]
It's there but it's just set to `1`.

This is the `src` value for the different versions using the code above:

3.0.2: https://calendly.com/perdoo/talk-to-sales?hide_event_type_details=1&hide_landing_page_details=1&background_color=#fff&hide_event_type_details=1&hide_landing_page_details=1&primary_color=#05A9F4&text_color=#14203C&name=Jonny%20Morrice&email=xx@perdoo.com&embed_type=Inline&embed_domain=1

2.1.0: https://calendly.com/perdoo/talk-to-sales?embed_domain=localhost%3A3000&embed_type=Inline&hide_event_type_details=1&hide_landing_page_details=1&background_color=&name=Jonny%20Morrice&email=xx%40perdoo.com

**Comment by tcampb** [comment]
Thanks for providing the full url, I think I see the issue. When I copied the `3.0.2` url I was automatically redirected to the following url which has the `embed_domain` query parameter removed:

https://calendly.com/perdoo/talk-to-sales?hide_event_type_details=1&hide_landing_page_details=1&background_color=&month=2022-04

It appears that this issue is occurring because the background_color property includes `#`. Removing `#` from the pageSetting color properties should resolve the issue.

```tsx
{
  "backgroundColor": "ffffff",
  "hideEventTypeDetails": false,
  "hideLandingPageDetails": false,
  "primaryColor": "00a2ff",
  "textColor": "4d5055",
  "hideGdprBanner": true
}
```

**Comment by tcampb** [comment]
@ankitjena - do you have a link to a public repository, or [stackblitz](https://stackblitz.com/) example application that you could share where you are able to re-create this issue? I'm not able to reproduce the `CalendlyEventListener` issue locally.

**Comment by ankitjena** [comment]
@tcampb False alarm. My bad the issue was on my end, a simple javascript undefined error, the callback was being fired properly.

**Comment by jmorrice** [comment]
Thanks @tcampb, can confirm that did the trick!
