### ISSUE TITLE
'CalendlyEventListener' cannot be used as a JSX component  React 18

### ISSUE THREAD

**Issue by christianiancuya** [tcampb/react-calendly#112]
![image](https://user-images.githubusercontent.com/96082705/164061229-8f1574e5-b3fb-44a0-beee-7ce212fb6908.png)

**Comment by christianiancuya** [comment]
If I change render(): {} | null -> ReactNode in node_modules, error disappeared. how to resolve this issue?

**Comment by tcampb** [comment]
Thanks for creating this github issue @christianiancuya. 

I just published version `4.0.0` which replaces the `CalendlyEventListener` component with the [`useCalendlyEventListener` ](https://github.com/tcampb/react-calendly/blob/master/src/components/hooks/useCalendlyEventListener.ts) hook. Could you try upgrading and replacing the component version with the new `useCalendlyEventListener` hook?

**Comment by christianiancuya** [comment]
Thanks for your update @tcampb 
However, I can't run this hook. Can you help me how to use it instead of CalendlyEventListerner in this code?

<CalendlyEventListener
    onEventScheduled={onEventScheduled}
    onDateAndTimeSelected={() => setTimeSelected(true)}
    {...{ children: widget }}
  />

**Comment by christianiancuya** [comment]
This is really working well. thanks @tcampb
