### ISSUE TITLE
How to use useCalendlyEventListener

### ISSUE THREAD

**Issue by egluhbegovic** [tcampb/react-calendly#114]
Hey,

I have react-calendly v4 and using it inside next.js

I have the following component:

On Stackoverflow: https://stackoverflow.com/questions/72171635/usecalendlyeventlistener-not-receiving-events

```
const CalendlyWidget = observer(
	({
		visitTypeForSpecificEvent,
		onScheduled,
		calendlyProfileUrl,
		prefill
	}: IProps) => {
		const recordEvent = (e: EventScheduledEvent) => {
			console.log('Event Recorded');
			onScheduled(e.data.payload.event.uri);
		};

		useCalendlyEventListener({
			onEventScheduled: recordEvent
		});

		return (
			<div>
				<InlineWidget
					url={calendlyProfileUrl}
					pageSettings={{
						hideGdprBanner: true,
						primaryColor: 'FF585B'
					}}
					prefill={prefill}
				/>
			</div>
		);
	}
);

export default CalendlyWidget;

```

The inline widget is working as expected but the useCalendlyEventListener is not being triggered at all?

Can anyone provide some assistance?

**Comment by tcampb** [comment]
@egluhbegovic - could you provide a link to a public repository (or create a [stackblitz](https://stackblitz.com/) project) that re-creates the issue? I wasn't able to re-create the issue on the [storybook site](https://tcampb.github.io/react-calendly/?path=/story/components--calendlyeventlistener).

**Comment by egluhbegovic** [comment]
The issue has gone away, think there was a https:// missing in the URL being fed to the widget and that made the difference. Though I am not sure how that impacted the listener as the https:// is part of the calendly profile url.

Anyways its working no.w
