### ISSUE TITLE
How to use use useCalendlyEventListener

### ISSUE THREAD

**Issue by oalbacha** [tcampb/react-calendly#115]
Hello, 
Is it possible to share some code examples of how useCalendlyEventListener is used in nextjs? I'm not able to find any inspirations or uses online. Thanks so much!

**Comment by tcampb** [comment]
Hi @oalbacha -

I'm not very familiar with nextjs, but I used the stackblitz example project template (with `react-calendly`)  [here](https://stackblitz.com/edit/nextjs-fzkqnx?file=pages/index.js) and the `useCalendlyEventListener` is currently working. Is the `useCalendlyEventListener` hook not working in your nextjs project?

If so, could you provide a link to the code and I can look into the issue further.

**Comment by oalbacha** [comment]
The stackblitz example is exactly what I was after. Thank you!!
