### ISSUE TITLE
Move the "X" closing button in the UI

### ISSUE THREAD

**Issue by Sed9yDataBank** [tcampb/react-calendly#118]
👋 is it possible to change the place of the "X" close button of the Calendly popup? 

![Screen Shot 2022-05-18 at 12 43 45 PM](https://user-images.githubusercontent.com/58634448/169031281-9a4906a5-c45f-4af9-b47c-7cb788e90bb9.png)

I had several complains where users would say that the Calendly popup close button "is hard to notice"

Example: I was thinking of adding a rectangle closing button a bit to the lower left, instead of the "X" white icon in the top. What steps to follow to achieve that? I feel like it would be impossible to manipulate the Calendly Iframe? 

Thanks.

**Comment by tcampb** [comment]
Hi @Sed9yDataBank - 

The modal design is currently a direct copy of [Calendly's popup widget](https://help.calendly.com/hc/en-us/articles/223147027-Embed-options-overview); as a result the modal component does not provide many customization options.

I would recommend creating a custom modal and using the [`InlineWidget`](https://tcampb.github.io/react-calendly/?path=/story/components--inlinewidget) component as the modal content. This will allow you to embed Calendly on your react app with a custom modal design.

Linked below is an example of this using [`react-modal`](https://github.com/reactjs/react-modal):

https://stackblitz.com/edit/react-swinzv

**Comment by Sed9yDataBank** [comment]
@tcampb awesome! thank you for attaching the example.
