### ISSUE TITLE
Documentation for useCalendlyEventListener could be more descriptive

### ISSUE THREAD

**Issue by jzemke** [tcampb/react-calendly#120]
I'm struggling to figure out how to implement `useCalendlyEventListener` to handle events (specifically `onEventScheduled`). Any clarification you could provide in the documentation would be much appreciated!

**Comment by tcampb** [comment]
Hey @jzemke,

I just added the following code example to the README, let me know if there is any additional information that would be helpful.

```jsx
import React from "react";
import { useCalendlyEventListener, InlineWidget } from "react-calendly";

const App = () => {
  useCalendlyEventListener({
    onProfilePageViewed: () => console.log("onProfilePageViewed"),
    onDateAndTimeSelected: () => console.log("onDateAndTimeSelected"),
    onEventTypeViewed: () => console.log("onEventTypeViewed"),
    onEventScheduled: (e) => console.log(e.data.payload),
  });

  return (
    <div className="App">
      <InlineWidget url="https://calendly.com/your_scheduling_page" />
    </div>
  );
};

export default App;
```

The structure of the `onEventScheduled` data object can be found [here](https://github.com/tcampb/react-calendly#how-can-i-access-the-event-details-when-an-event-is-scheduled)

**Comment by jzemke** [comment]
This makes it quite clear, really appreciate the update.
