### ISSUE TITLE
Not able to integrate `PopupWidget`  with react native.

### ISSUE THREAD

**Issue by SanketW12** [tcampb/react-calendly#121]
Hi  
Can you give me some examples of how I can integrate with `PopupWidget` react native?

**Comment by tcampb** [comment]
Hi @SanketW12,

Unfortunately, `react-calendly` is not currently compatible with `react-native` as it renders the Calendly scheduling page using an `iframe`.

I would recommend using [`react-native-webview`](https://github.com/react-native-webview/react-native-webview) to render the scheduling page in your react native application.

Below is an example of showing the `WebView` component on button press in react native:

```javascript
import React from "react";
import { View, Button } from "react-native";
import { WebView } from "react-native-webview";

export default function App() {
  const [showWebView, setShowWebview] = React.useState();

  if (showWebView) {
    return <WebView source={{ uri: "https://calendly.com/acmesales" }} />;
  }

  return (
    <View style={{ marginTop: 50 }}>
      <Button
        onPress={() => setShowWebview(true)}
        title="Click here to schedule!"
      />
    </View>
  );
}
```

**Comment by SanketW12** [comment]
Hi @tcampb, Thank you for the reply.

**Comment by feraswfares** [comment]
Hi @tcampb 
is there any way that i can get Calendly response from WebView cause  I need the date and time selected by the user

**Comment by tcampb** [comment]
@feraswfares - Yes, you can add an event listener to the window to listen for Calendly events:

```javascript
function isCalendlyEvent(e) {
  return e.origin === "https://calendly.com" && e.data.event && e.data.event.indexOf("calendly.") === 0;
};
 
window.addEventListener("message", function(e) {
  if(isCalendlyEvent(e)) {
    /* Example to get the name of the event */
    console.log("Event name:", e.data.event);
    
    /* Example to get the payload of the event */
    console.log("Event details:", e.data.payload);
  }
});
```
You can see Calendly event payload [here](https://developer.calendly.com/api-docs/ZG9jOjI3ODM2MTAz-notifying-the-parent-window). As you can see in the documentation, the date and time scheduled is not directly available in the payload. You'll need to use Calendly's v2 api to get additional details about the scheduled event.

If the event listener is **not** working in your WebView, you may need to add an `embed_domain` query parameter to your Calendly url. See the stackoverflow post below for additional details.

https://stackoverflow.com/questions/69017075/wkwebview-addeventlistener-not-receiving-calendly-events/69017867#69017867

**Comment by feraswfares** [comment]
@tcampb  Thank you for the reply
actually i am using react native not react i try to add listener to web view but it is not working 

```
     <WebView
            source={{
              uri: '',
            }}
            injectedJavaScript={`window.addEventListener("message", function(e) {console.log("Event name:", e);});`}

            onMessage={(event) => {
              console.log('eee', event);
            }}
          />
```

**Comment by tcampb** [comment]
@feraswfares - would you be able to share the entire code snippet including the Calendly webview? I'm not very familiar with web view's in React Native but my guess would be that the event listener code would need to be in the same web view as the Calendly code as seen in the first code example in the stackoverflow post below:

https://stackoverflow.com/questions/69017075/wkwebview-addeventlistener-not-receiving-calendly-events/69017867#69017867
