### ISSUE TITLE
ReferenceError using PopupButton in MDX

### ISSUE THREAD

**Issue by mbaytas** [tcampb/react-calendly#122]
I am using react-calendly inside a MDX file with Next.js, as follows.

My file `mypage.mdx`:

    import { PopupButton } from "react-calendly";

    <PopupButton
    url="https://calendly.com/your_scheduling_page"
    rootElement={document.getElementById("main")}
    text="Click here to schedule!"
    textColor="#ffffff"
    color="#00a2ff"
    />

Getting the following error:

    ReferenceError: document is not defined

What is the best solution for this?

**Comment by tcampb** [comment]
You can wrap the `PopupButton` component in a function so that `document.getElementById` isn't called until the document object is available.

Example:

https://stackblitz.com/edit/nextjs-ysa2ui?file=pages/index.mdx
