### ISSUE TITLE
implementing in React Native 

### ISSUE THREAD

**Issue by bhojaniasgar** [tcampb/react-calendly#124]
i am implementing calendy in react native i have create a HTML page and added the script but i am unable to use the prefilled functionality 

<WebView   source={{    uri: 'file:///android_asset/html/calendly.html'}}/>

**Comment by tcampb** [comment]
Hey @bhojaniasgar, 

Could you include the code from `file:///android_asset/html/calendly.html`? This will help me determine why the prefill option isn't working.

**Comment by bhojaniasgar** [comment]
below is the code 

<html>
<head>
    <div class="calendly-inline-widget" style="width:100%;height:100%;" data-auto-load="false">
        <script type="text/javascript" src="https://assets.calendly.com/assets/external/widget.js" mim></script>
        
        <script>
            Calendly.initInlineWidget({
                url: 'https://calendly.com/asgar-b/30min',
                prefill: {
                    name: `name`,
                    email: "john@doe2.com",
                    customAnswers: {
                        a1: "Yes",
                    }
                }
            });
        </script>
    </div>
</head>

</html>

**Comment by bhojaniasgar** [comment]
below is the code  which is Added 

<html>
<head>
    <div class="calendly-inline-widget" style="width:100%;height:100%;" data-auto-load="false">
        <script type="text/javascript" src="https://assets.calendly.com/assets/external/widget.js" mim></script>
        
        <script>
            Calendly.initInlineWidget({
                url: 'https://calendly.com/asgar-b/30min',
                prefill: {
                    name: `name`,
                    email: "john@doe2.com",
                    customAnswers: {
                        a1: "Yes",
                    }
                }
            });
        </script>
    </div>
</head>

</html>

**Comment by bhojaniasgar** [comment]
> below is the code
> 
> <script type="text/javascript" src="https://assets.calendly.com/assets/external/widget.js" mim></script> <script> Calendly.initInlineWidget({ url: 'https://calendly.com/asgar-b/30min', prefill: { name: `name`, email: "john@doe2.com", customAnswers: { a1: "Yes", } } }); </script>

i have created a HTML file and link with WEB VIEW 

or else please help me how to integrate calendy in REACT-NATIVE

**Comment by tcampb** [comment]
@bhojaniasgar - can you try wrapping your Calendly script tags in an html `body` tag?

The [`widget.js`](https://assets.calendly.com/assets/external/widget.js) code references the body tag so I'm wondering if the script fails since it runs before the body tag exists. For example, when I removed the `body` tag it stopped working.

example:

```jsx
<WebView
      source={{
        html: `
        <body>
          <script type="text/javascript" src="https://assets.calendly.com/assets/external/widget.js" mim></script> 
          <script> Calendly.initInlineWidget({ url: 'https://calendly.com/asgar-b/30min', prefill: { name: "name", email: "john@doe2.com", customAnswers: { a1: "Yes", } } }); </script>
        </body>
      `,
      }}
    />
```

**Comment by bhojaniasgar** [comment]
hello @tcampb  
i am unable to give height and width and How can i pass name From stte to Prefill Data

**Comment by tcampb** [comment]
> i am unable to give height and width

You can wrap your `Webview` in a `View` container component and adjust the height / width of the container.

```jsx
<View style={{ height: 500, width: 500 }}>
   {/* Webview goes here */}
</View>
```

> How can i pass name From state to Prefill Data

Since the html is using a [template literal you can use string interpolation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) to pass the state variables to the Calendly javascript function (see example below):

```jsx
export default function App() {
  const [name, setName] = React.useState("name");
  const [email, setEmail] = React.useState("test@test.com");
  const [answerOne, setAnswerOne] = React.useState("Test123");

  return (
    <View style={{ height: 500, width: 500 }}>
      <WebView
        source={{
          html: `
          <body>
            <script type="text/javascript" src="https://assets.calendly.com/assets/external/widget.js" mim></script> 
            <script> Calendly.initInlineWidget({ url: 'https://calendly.com/asgar-b/30min', prefill: { name: "${name}", email: "${email}", customAnswers: { a1: "${answerOne}", } } }); </script>
          </body>
        `,
        }}
      />
    </View>
  );
}
```

**Comment by bhojaniasgar** [comment]
@tcampb 
it   worked for me

**Comment by bhojaniasgar** [comment]
Hello @tcampb 

Is it possible that we can get the date and time. Which user selected in react native 
From the above code 
If yes then please help me regarding that

**Comment by tcampb** [comment]
@bhojaniasgar - the [Calendly iframe message](https://developer.calendly.com/api-docs/ZG9jOjI3ODM2MTAz-notifying-the-parent-window) that is sent when a user selects a date / time does not include this information.

You would need to use the uri in the message sent from the iframe **after** the event is scheduled to determine what date / time was scheduled.

```javascript
{
  event: "calendly.event_scheduled",
  payload: {
    event: {
      uri: "https://api.calendly.com/scheduled_events/ABCDABCDABCDABCD"
    },
    invitee: {
      uri: "https://api.calendly.com/api/v2/scheduled_events/ABCDABCDABCDABCD/invitees/ABCDABCDABCDABCD"
    }
  }
}
```

**Comment by bhojaniasgar** [comment]
@tcampb  how can we use this in react native

**Comment by bhojaniasgar** [comment]
@tcampb  
please let me know how to do this ?
Waiting for solution 

Thanks

**Comment by tcampb** [comment]
@bhojaniasgar - I'm not exactly sure how this works within a react native webview since the `react-calendly` library does not support react native, but my guess is that you would need to use the [`injectedJavascript`](https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#injectedjavascript) property to add the event listener code.

```jsx
const INJECTED_JAVASCRIPT = `(function() {
function isCalendlyEvent(e) {
  return e.data.event &&
         e.data.event.indexOf('calendly') === 0;
};
 
window.addEventListener(
  'message',
  function(e) {
    if (isCalendlyEvent(e)) {
      console.log(e.data);
    }
  }
);


})();`;

export default function App() {
  const [name, setName] = React.useState("name");
  const [email, setEmail] = React.useState("test@test.com");
  const [answerOne, setAnswerOne] = React.useState("Test123");

  return (
    <View style={{ height: 500, width: 500 }}>
      <WebView
        injectedJavaScript={INJECTED_JAVASCRIPT}
        source={{
          html: `
          <body>
            <script type="text/javascript" src="https://assets.calendly.com/assets/external/widget.js" mim></script> 
            <script> Calendly.initInlineWidget({ url: 'https://calendly.com/asgar-b/30min', prefill: { name: "${name}", email: "${email}", customAnswers: { a1: "${answerOne}", } } }); </script>
          </body>
        `,
        }}
      />
    </View>
  );
}
```

**Comment by Shikhar2404** [comment]
can i change the amount of money dynamically from webview to calendly? or is there any way i can send calculate price from my RN and send to calendly's event
