### ISSUE TITLE
Is there a way to know when an event was rescheduled?

### ISSUE THREAD

**Issue by oskrgg** [tcampb/react-calendly#125]
Rescheduling events from EmbedAPI don't trigger the `onEventScheduled`
How do I know when an event has been rescheduled?

```js
useCalendlyEventListener({
    onEventScheduled: (e) => console.log('Only when scheduling no rescheduling'),
  });

**Comment by tcampb** [comment]
Hey @oskrgg, 

It seems like this is a bug with Calendly's scheduling page; it appears that all other events are fired except "event_scheduled" in the reschedule flow. The only workaround I can think of is to use a webhook to try and determine if the event was rescheduled - https://developer.calendly.com/api-docs/c1ddc06ce1f1b-create-webhook-subscription

**Comment by tcampb** [comment]
Here is the response I received from Calendly's support team regarding this issue:

> That is the expected behavior at this time. While it is possible to embed Calendly cancelation and reschedule links, the calendly.event_scheduled event will not fire on these pages. There is currently no event fired when a rescheduled event is confirmed or a cancelation is confirmed.

> It is also expected that calendly.event_type_viewed and calendly.date_and_time_selected will fire on the reschedule page.
 
> We do have an internal feature request looking into this, but currently the workaround would be to create a webhook just as you suggested.
