### ISSUE TITLE
React Calendly is compatible with react native?

### ISSUE THREAD

**Issue by tannguyen** [tcampb/react-calendly#126]
I saw this issue https://github.com/tcampb/react-calendly/issues/103, in this thread @tcampb said
```
Yes, all of the components in the react-calendly library are compatible with react native. If you run into any issues integrating react-calendly into your react native application please let me know, I'd be happy to look into the issue further.
```

By the way, this library:
- Use the root dom to hook up the modal -> this is a web mechanism, native doesn't have this => How can this library run in native?
- Many places in source are using div, how can it be used in native?

**Comment by tcampb** [comment]
Thanks for creating this issue @tannguyen! I've updated my comment (https://github.com/tcampb/react-calendly/issues/103) to state that `react-calendly` is **not** compatible with react native.

**Comment by Shikhar2404** [comment]
can i change the amount of money dynamically from webview to calendly? or is there any way i can send calculate price from my RN and send to calendly's event. i want to give discount to users
