### ISSUE TITLE
How to prevent Google Analytics loading from Calendly

### ISSUE THREAD

**Issue by AdrienFery** [tcampb/react-calendly#129]
Any idea how to prevent Calendly to load Google Analytics?

**Comment by tcampb** [comment]
Hi Adrien, I'm not aware of any settings that allow you to prevent Calendly from loading Google Analytics. 

Calendly's V2 api provides an endpoint that allows you to retrieve an [event type's available time slots](https://developer.calendly.com/api-docs/6a1be82aef359-list-event-type-available-times). This would allow you to load the available time slots without loading the Google Analytics library. That said, the invitee would still need to navigate to the Calendly scheduling page to confirm the appointment as the api does not provide an endpoint for scheduling.

**Comment by AdrienFery** [comment]
Hi @tcampb,

Thanks for your answer!
