### ISSUE TITLE
Embed script outdated?

### ISSUE THREAD

**Issue by audiolion** [tcampb/react-calendly#13]
I believe the embed script that Calendly uses has changed, as a result there seems to be some CSS missing related to the calendly-spinner and three bouncing dots for the InlineWidget.

**Comment by tcampb** [comment]
Thanks for finding this @audiolion! This should be fixed now (see https://github.com/tcampb/react-calendly/commit/ca6597ce37cc0dc14a273dd13e7acc0e8010be94), I had forgotten to load the stylesheet in the `InlineComponent` 😞

**Comment by audiolion** [comment]
Yep, working as expected now, thanks for the quick update 💯
