### ISSUE TITLE
Detail of the event from useCalendlyEventListener

### ISSUE THREAD

**Issue by habibi-binary** [tcampb/react-calendly#130]
Hello,

So I have this page that shows the Calendly calendar of a registered user. And the visitor can do the booking.

I have already set the `useCalendlyEventListener` to get the event of booking, and the passed value looks like this :
```
{
  "event": {
    "uri": "https://api.calendly.com/scheduled_events/1797ce4b-a302-4206-80c1-xxxxxx"
  },
  "invitee": {
    "uri": "https://api.calendly.com/scheduled_events/1797ce4b-a302-4206-80c1-xxxxxx/invitees/feaeaede-2deb-4985-9419-xxxxxx"
  }
}
```

The question is, how can I get the detail of the event and invitee of the booking since the visitor might don't have Calendly account?

I'm quite sure, the provided value on `event.uri` field require the `access_token` to be accessed, as you described [here](https://developer.calendly.com/api-docs/e2f95ebd44914-get-event)

Thanks

**Comment by tcampb** [comment]
To retrieve data from the `event.uri`, you'll need a backend server that can securely store your Calendly account's access token. 

I've created an example using Next.js [here](https://stackblitz.com/edit/nextjs-dwsdjj?file=pages/index.js). Please note that for this example to work you'll need to replace the Calendly url and Calendly access token variables.

Let me know if you have any additional questions regarding the example app.

**Comment by LeiYao123** [comment]
@tcampb  

excuse me
I want to get the contents filled in the form, such as Selected date, name, email, etc

As shown in the figure below
![image](https://user-images.githubusercontent.com/99799032/191258301-67e8c4b5-bc9e-45a9-9583-ea9078856231.png)

According to the above statement, I did not get the data I wanted through the API

![image](https://user-images.githubusercontent.com/99799032/191259186-d6d5503a-de92-4eb7-8314-b61957f46369.png)

**Comment by tcampb** [comment]
@LeiYao123 - to retrieve the form information you'll need to add [`/invitees`](https://developer.calendly.com/api-docs/eb8ee72701f99-list-event-invitees) to the scheduled events endpoint:

`https://api.calendly.com/scheduled_events/${id}/invitees`

**Comment by tcampb** [comment]
@LeiYao123 - the time can be found in your original screenshot under the object key `start_time`. Please note that the `start_time` returned in the response is in UTC time.

**Comment by LeiYao123** [comment]
@tcampb Thank you very much😁

**Comment by tcampb** [comment]
@LeiYao123 - Np! Also, I just realized that your API key is currently visible in the screenshot above; you can visit [https://calendly.com/integrations/api_webhooks](https://calendly.com/integrations/api_webhooks) to revoke the token in the screenshot.
