### ISSUE TITLE
PopupButton does not have onClick handler

### ISSUE THREAD

**Issue by bymoe** [tcampb/react-calendly#131]
This :point_down: 
```
<PopupButton onClick={ () => {
  console.log("Clicked");
} } />
``` 
does not work

**Comment by tcampb** [comment]
Hi @bymoe - 

If you need to add custom logic to the `onClick` method you can do so by creating a custom button component - see [here](https://github.com/tcampb/react-calendly#how-do-i-create-a-custom-button-that-triggers-a-pop-up-scheduler). The `PopupModal` component used in this example is the same component used by the `PopupButton`.
