### ISSUE TITLE
[Feature Request] Disable changing pre-filled email address

### ISSUE THREAD

**Issue by watadarkstar** [tcampb/react-calendly#134]
**Why**

We don't want our users to change the pre-filled email address. I'm not sure if this is possible. Let me know if it is or isn't.

**Example**

```
<InlineWidget
            styles={{
              height: "850px",
              position: "relative",
              bottom: "60px",
            }}
            prefill={{
               email: { value: "hello@gmail.com", disabled: true }
            }}
            url={calendlyUrl}
            pageSettings={calendlyPageSettings}
          />
```

**Comment by tcampb** [comment]
@watadarkstar - the Calendly [embed api](https://help.calendly.com/hc/en-us/articles/223147027?tab=advanced#3) does not currently provide a way to disable any of the inputs on the scheduling page.

One option would be to store the original email address as a utm parameter, for example:

```tsx
<InlineWidget
            styles={{
              height: "850px",
              position: "relative",
              bottom: "60px",
            }}
            url={calendlyUrl}
            pageSettings={calendlyPageSettings}
            utm={{ utmContent: "hello@gmail.com" }}
          />
```

This provides an easier way to track the user that scheduled as the utm parameter value can only be changed in the url and not in the scheduling form.

**Comment by watadarkstar** [comment]
@tcampb Thanks for the suggestion!

Is there a way to validate that the email they entered is the same one the application passed as a prefill?

For example by adding a check in a callback method?

```
useCalendlyEventListener({
    onEmailChanged: (email) => if (prefill.email !== email) alert("The email cannot be changed"),
  });
```

**Comment by tcampb** [comment]
@watadarkstar - the [embed api events](https://developer.calendly.com/api-docs/ZG9jOjI3ODM2MTAz-notifying-the-parent-window) don't currently support notifying the parent window of any changes within the scheduling form; as a result, we wouldn't be able to detect if any of the field values changed during the scheduling process.

**Comment by watadarkstar** [comment]
Closing since there is no way to do this :(

**Comment by doublejosh** [comment]
You could...
- capture the `data.payload` with the `onEventScheduled` event listener
- send the API endpoints it gives you to your own cloud function (or active server) endpoint
- use a token and the endpoints to grab the data
- send a reply to the client with your validation

It's very ridiculous that the embed doesn't share the form submission data with the client... but the above is the horrific workaround.
