### ISSUE TITLE
The Components that require specifying the rootElement property don't work on Next js

### ISSUE THREAD

**Issue by kaidezen** [tcampb/react-calendly#138]
I'm trying to use the PopupButton, but it doesn't work. The error is thrown because "document" is only available inside the browser and not on the server. Next js executes this code on the server side and that's why the error is thrown.

Any easy fix for this?

(Great npm btw!)

**Comment by tcampb** [comment]
You can render the `PopupButton` after `useEffect` is run to ensure that the document object is available:

```javascript
export default function Calendly(selector = "#root") {
  const ref = useRef();
  const [mount, setMount] = useState(false);

  useEffect(() => {
    ref.current = document.querySelector(selector);
    setMount(true);
  }, [selector]);

  return mount ? (
    <PopupButton
      url="https://calendly.com/acmesales"
      rootElement={document.getElementById(selector)}
      text="Click here to schedule!"
    />
  ) : null;
}
```

**Comment by kaidezen** [comment]
Thank you so much for such a quick reply. Calendly should be paying you for this!

Unfortunately (maybe I did something wrong), it didn't work and I got a new error:

"Unhandled Runtime Error
SyntaxError: Failed to execute 'querySelector' on 'Document': '[object Object]' is not a valid selector."

Here are screenshots of the full error:

https://ibb.co/16s4CQX
https://ibb.co/8NDVCPt
https://ibb.co/BqNGFx9

(Strangely the error only shows on the browser. On VS Code's terminal it just says compiled successfully).

I believe I did it how I was supposed to. I created a component with your code and then placed that component where I want the button to be.

`import React, { useRef, useEffect, useState } from 'react';
import { PopupButton } from "react-calendly";

export default function Calendly(selector = "#root") {
    const ref = useRef();
    const [mount, setMount] = useState(false);
  
    useEffect(() => {
      ref.current = document.querySelector(selector);
      setMount(true);
    }, [selector]);
  
    return mount ? (
      <PopupButton
        url="https://calendly.com/myupself/consulting-session"
        rootElement={document.getElementById(selector)}
        text="Click here to schedule!"
      />
    ) : null;
  }`

Did I do something wrong or misunderstand how I was supposed to apply the code?

**Comment by tcampb** [comment]
Based on the error, it looks like the selector variable is an object instead of a string.

Try changing the code to the following:

```javascript
export default function Calendly({ selector }) {
  const ref = useRef();
  const [mount, setMount] = useState(false);

  useEffect(() => {
    ref.current = document.querySelector(selector);
    setMount(true);
  }, [selector]);

  return mount ? (
    <PopupButton
      url="https://calendly.com/acmesales"
      rootElement={document.getElementById(selector)}
      text="Click here to schedule!"
    />
  ) : null;
}
```

Then in another file you can use the code above:

```javascript
<Calendly selector="#root" />
```

**Comment by kaidezen** [comment]
Thank you so much for the new suggestion.

Just tried it and got this error:

"Unhandled Runtime Error
Error: Target container is not a DOM element."

Perhaps this npm just isn't compatible with Next JS? (However, just FYI, it used to work on a prior version (the react-calendly 2.0 I think, with version 9.5 of Next JS). Back when the component was called "openPopupWidget" instead of "PopupButton").

**Comment by tcampb** [comment]
@kaidezen - do you have a link to a public Github repository with the code? The example code above assumes that there is an HTML element with an `id` of root. You'll need to change the selector to match your code, or add an element with an id of `root`.

```javascript
<div id="root">
   <Calendly selector="#root" />
</div>
```

**Comment by kaidezen** [comment]
I tried to add the id "root" to both the whole section and then to just a div wrapping the Calendly component but still got the same error.

I created a new version of my code with barely any files just so it's easier/faster for you to understand my code/organization.

Here it is: https://github.com/kaidezen/calendly-button-test

The Calendly component file is under the components folder and it is being used in the above-the-fold.js file under the "sections" folder.

Let me know if you need anything else at all and thanks again

**Comment by tcampb** [comment]
Ah, sorry for the confusion, it looks like I had an error in my code above. 

This [line](https://github.com/kaidezen/calendly-button-test/blob/d63a9fac6692a11c8380632b68dabd5080727ed3/components/calendly.js#L16) should be `document.querySelector(selector)`, **not** `getElementById`.

Updated code:


```javascript
export default function Calendly({ selector }) {
  const ref = useRef();
  const [mount, setMount] = useState(false);

  useEffect(() => {
    ref.current = document.querySelector(selector);
    setMount(true);
  }, [selector]);

  return mount ? (
    <PopupButton
      url="https://calendly.com/acmesales"
      rootElement={document.querySelector(selector)}
      text="Click here to schedule!"
    />
  ) : null;
}
```

**Comment by kaidezen** [comment]
Wow, no need to apologize at all, it worked! Thank you so much. I never could've done it without your help.

I'll close this issue, but before I do, do you have any website like those where you "buy" people a coffee? Or anything like that. Just to repay you for all the amazing help.

**Comment by tcampb** [comment]
Awesome, glad to hear that it worked :tada:!

> I'll close this issue, but before I do, do you have any website like those where you "buy" people a coffee? Or anything like that. Just to repay you for all the amazing help.

I really appreciate the offer, but no need for repayment! Having this GitHub issue documented will help others fix the issue in the future, so that's repayment enough :smile:

**Comment by kaidezen** [comment]
You're amazing, man. Thank you for everything!
