### ISSUE TITLE
React Native

### ISSUE THREAD

**Issue by sandirr** [tcampb/react-calendly#142]
Is there a way to use react-calendly in react native? I really need calendlyEventListener feature but in react native

I tried use webview in RN
InlineWidget has shown
but eventListener doesn't work

```
const injectedJS = `
    Calendly.initInlineWidget({
      url: 'https://calendly.com/mylink',
      prefill: {
        name: "${data.signupInfo.firstName}",
        email: "${data.signupInfo.email}",
      }
    });
    
    function isCalendlyEvent(e) {
      return e.origin === "https://calendly.com" && e.data.event && e.data.event.indexOf("calendly.") === 0;
    };
    
    window.addEventListener("message", function(e) {
      window.alert('hey please work!')
       if (isCalendlyEvent(e)) {
          
          if( Object.keys(e.data.payload).length ) {
             window.alert(e.data.payload);
          } else {
             // ignore
          }
       } else {
          // ignore
       }
    });
  `;
```

**Comment by tcampb** [comment]
@sandirr - can you try adding an `embed_domain` query parameter to your url? Calendly will only post a message to the parent window if the embed domain is defined - [https://stackoverflow.com/a/69017867/13641812](https://stackoverflow.com/a/69017867/13641812)

```javascript
 Calendly.initInlineWidget({
      url: 'https://calendly.com/mylink?embed_domain=1',
      prefill: {
        name: "${data.signupInfo.firstName}",
        email: "${data.signupInfo.email}",
      }
    });
```

[source](https://github.com/tcampb/react-calendly/blob/master/src/calendly.tsx#L164)

**Comment by Shikhar2404** [comment]
can i change the amount of money dynamically from webview to calendly? or is there any way i can send calculate price from my RN and send to calendly's event. i want to give discount to users
