### ISSUE TITLE
The components themselves should throw an error if "rootElement" is missing

### ISSUE THREAD

**Issue by Stephane-Ag** [tcampb/react-calendly#143]
I just came back from a multi-hour chase just to realize this was my issue.
This happened after updating a bunch of packages so it wasn't apparent in any way that this was the issue.
This goes for `PopupButton` and anything else using `PopupModal`.

**Comment by tcampb** [comment]
Thanks for the feedback @Stephane-Ag. I've added your suggestion to the `PopupModal` component, which is used by the `PopupWidget` and `PopupButton`.

https://github.com/tcampb/react-calendly/blob/master/src/components/PopupModal/Modal.tsx#L14-L16

This change will be available in version 4.1.1
