### ISSUE TITLE
question: how to remove calendly sign up footer?

### ISSUE THREAD

**Issue by da1z** [tcampb/react-calendly#144]
hey. is there a way to remove this footer from event confirmation page?
<img width="915" alt="Screen Shot 2023-01-18 at 7 37 44 PM" src="https://user-images.githubusercontent.com/4012422/213349757-7717d1ee-3c88-4711-aa08-b2eff5d63c5e.png">

**Comment by tcampb** [comment]
@da1z - To remove the footer from the event confirmation page you'll need to disable the Calendly branding setting in your [Account setting's page](https://help.calendly.com/hc/en-us/articles/223195448-Manage-your-account-settings-an-overview#manage-your-account-settings-an-overview-0-0). The Calendly embed code api does not currently provide a way to disable this setting.

To disable this setting your account will need to be using the Professional edition or higher:

https://calendly.com/pricing
