### ISSUE TITLE
Style error on iframe.

### ISSUE THREAD

**Issue by LucasBadico** [tcampb/react-calendly#15]
Hey guys we are having a style problem.
![image (4)](https://user-images.githubusercontent.com/16516889/86516893-da4a5680-bdfa-11ea-8efb-a9d52cac9e30.png)
Do you have faced this problem before?

**Comment by tcampb** [comment]
Hi @LucasBadico, 

The scrollbar appears when the iframe content's height exceeds the height of the parent container. Unfortunately, this is not something we can change within the `react-calendly` library as we cannot change the iframe content's height dynamically based on the parent window's height. That said, this issue has been brought up on Calendly's idea portal and I would encourage you to upvote the idea [here](https://help.calendly.com/hc/en-us/community/posts/360032035073-Iframe-Resize-Parent-Window-Content-Height-Prevent-Double-Scroll-Bar).

**Comment by LucasBadico** [comment]
Thanks @tcampb, have upvoted. I will close this.

**Comment by tcampb** [comment]
@LucasBadico -

Version 4.3.1 updates the  `useCalendlyEventListener` hook to include an `onPageHeightResize` option.

This allows you to resize the parent container when the Calendly scheduling page's height changes. 

For example:

```jsx
import {
  InlineWidget,
  useCalendlyEventListener,
} from "react-calendly";

function App() {
  const [height, setHeight] = useState('500px');
  const onPageHeightResize = (e) => setHeight(e.data.payload.height);

  useCalendlyEventListener({
    onPageHeightResize
  })

  return (
    <>
      <InlineWidget
        styles={{ height }}
        url="https://calendly.com/acmesales"
      />
    </>
  );
}
```
