### ISSUE TITLE
Disable prefilled input

### ISSUE THREAD

**Issue by Ilansky** [tcampb/react-calendly#150]
I use react calendly, and my calendly is connected to salesforce.
My user takes an appointment when he is already logged in.
So I already have his name and email.
I use the prefill, but the user still has the ability to change his name and email.
Which means in salesforce the appointment will be associated to another lead.
How can I disable those field, as I want the name and email of the appointment to be consistent with the name and email registered with the logged account.

**Comment by tcampb** [comment]
@Ilansky - Unfortunately, Calendly's embed api does not support disabling the name / email fields in the scheduling form.

However, there is a `salesforce_uuid` parameter you can use to ensure that the appointment will be associated with the correct lead in Salesforce.

https://github.com/tcampb/react-calendly/blob/master/src/calendly.tsx#L42

```jsx
<PopupModal
   url="https://calendly.com/acmesales"
   utm={{ salesforce_uuid: '001' }}
   onModalClose={() => this.setState({ isOpen: false })}
   open={this.state.isOpen}
   rootElement={document.getElementById("root")}
 />
 ```

**Comment by dvargas92495** [comment]
@tcampb is Calendly's stance that they won't ever support disabling the inputs or just haven't done so yet?

If the former, then we would have to create our own UI and call the Calendly API ourselves for call bookings, which would decrease Calendly's exposure

**Comment by tcampb** [comment]
@dvargas92495 - I'm not sure whether or not this is something that will be implemented in Calendly. Since the prefill values are set via query parameters, the invitee could technically change them even if the input field is disabled; as a result, I'm not sure that the `react-calendly` library could prevent this behavior even if the fields were disabled.

**Comment by dvargas92495** [comment]
Sure, and even if it wasn't via query param, a technical user could right click inspect, remove disabled, and then change the value. We were hoping that disabled input would be an 80/20 solution that would solve most of the non-technical-user cases

**Comment by dvargas92495** [comment]
In Calendly's defense, I could see situations where I sign up for a platform with a personal email, but want to book the call with a work email, for example. So there are situations where allowing modifying of prefilled inputs could make sense, but I wouldn't say that's the norm
