### ISSUE TITLE
Update links in documentation 

### ISSUE THREAD

**Issue by TanveerAliS** [tcampb/react-calendly#151]
Team,

I really appreciate if you can updated links for [Scheduled Event Schema] and [Invitee Schema]

**Comment by tcampb** [comment]
This should now be fixed:

[https://github.com/tcampb/react-calendly/commit/08c8074bb7067dd6bc9360e5273397a21c70b521](https://github.com/tcampb/react-calendly/commit/08c8074bb7067dd6bc9360e5273397a21c70b521)

Thanks for letting us know about this issue :tada: !
