### ISSUE TITLE
React-calendly calendly.com refused to connect. This error is shown

### ISSUE THREAD

**Issue by Abubakarraza** [tcampb/react-calendly#152]
<div className="App">
      <InlineWidget url="https://calendly.com/your_scheduling_page" />
    </div>
    I used this code in my react project and it give me this error("calendly.com refused to connect.") in screen

**Comment by tcampb** [comment]
@Abubakarraza - are you able to share the Calendly url that you are using in the embed code?

If the url is not associated with a booking page Calendly will prevent the iframe from loading. For example, the url `https://calendly.com/acmesales` will work, but `https://calendly.com` will cause the error above.

**Comment by prateek1998** [comment]
@tcampb Is there any way to check whether the link is valid calendly link or not?

**Comment by tcampb** [comment]
@prateek1998 - you can use the [useCalendlyEventListener](https://github.com/tcampb/react-calendly#usecalendlyeventlistener) hook to detect if the Calendly link was loaded successfully.

The `onProfilePageViewed` or `onEventTypeViewed` event will be immediately fired when the iframe is loaded.

**Comment by onadeemdev** [comment]
@tcampb is there anyway to check if the link is invalid such as before the load or any event listener that lets us know of an error?

**Comment by tcampb** [comment]
@onadeemdev - not currently, but we could probably add an `onError` property to the iframe that can be passed in - [https://github.com/tcampb/react-calendly/blob/master/src/components/InlineWidget/InlineWidget.tsx#L63](https://github.com/tcampb/react-calendly/blob/master/src/components/InlineWidget/InlineWidget.tsx#L63)

I can open an issue for this later today.

**Comment by tcampb** [comment]
@onadeemdev - I looked into this further and it appears that the iframe `onError` event is not fired when a calendly link that does not exist is passed as a prop. As a result, I don't think we can detect if the link is invalid.

@obecker-csdisco - do you have a [code snippet](https://codepen.io/pen/) you could share where you're able to get the iframe onerror event to fire (example when a site is down)?

**Comment by obecker-csdisco** [comment]
You get a 404 error on the request. That should be enough to set a prop. I currently use a timeout to detect error, but that is not a reliable way...

**Comment by tcampb** [comment]
@obecker-csdisco - how are you accessing the request that returns a 404? The request is sent from the iframe which cannot be accessed by react-calendly since it is cross domain.

**Comment by obecker-csdisco** [comment]
I don't access it, I just see it in the console.
