### ISSUE TITLE
Error: Unable to post message to https://calendly.com. Recipient has origin https://www.{myDomainName}

### ISSUE THREAD

**Issue by AaronMassingham** [tcampb/react-calendly#156]
I'm getting a console error when opening the react-calendly modal popup:

`Error: Unable to post message to https://calendly.com. Recipient has origin https://www."mydomain"`

I was wondering if anyone had come across this error and if they've managed to rectify the issue?

TIA

**Comment by tcampb** [comment]
Hey @AaronMassingham, 

I haven't seen this error before, but I was able to recreate the error only when using the Safari browser. Based on this [stackoverflow post](https://stackoverflow.com/a/67403711/13641812), it appears that Safari blocks two-way cross-domain iFrame communication.

That said, the error that you are seeing is coming from an analytics library that Calendly is using and should not affect your application. If you notice that this error is affecting your application, let me know and I can open a support ticket with Calendly.
