### ISSUE TITLE
[Feature Request] support onEventCancelled and onEventRescheduled callbacks in the useCalendlyEventListener hook

### ISSUE THREAD

**Issue by israelfagundes** [tcampb/react-calendly#157]
I'm currently working on a project where I need to update some states on frontend so I cannot just simply use webhooks, and I noticed that reschedulings and cancellings dont trigger the onEventScheduled callback. Is there any chances of calendly team to implements callbacks for these two types of interactions?

**Comment by tcampb** [comment]
Hey @israelfagundes,

I'm not sure if Calendly plans on implementing `window.postMessage` on the cancel / reschedule event flows. This was the response I received from their support team previously: 

[https://github.com/tcampb/react-calendly/issues/125#issuecomment-1218628003](https://github.com/tcampb/react-calendly/issues/125#issuecomment-1218628003)

Out of curiosity, how are you saving the reschedule / cancel uuid on the frontend? Are you saving it in localStorage after the users schedule from your site?

**Comment by israelfagundes** [comment]
Thanks for answering me @tcampb! Kinda sad to read that but ok, I'll see what I can do here.

About the reschedule / cancel uuid, I have the base URLs from both calendly forms, so I'm just saving the invitee id that I get on the payload from onEventScheduled callback on my database and using it to compose the event cancelling/rescheduling form url to use on calendly iframe.

**Comment by tcampb** [comment]
Thanks for the additional info @israelfagundes!

It's definitely not a great solution, but one option would be to poll the reschedule url (https://calendly.com/reschedulings/AAAAAAAAAAAAAAAA) to check if the link is still active. This endpoint does not require authentication.

Again, not a great solution but it's the only workaround I can think of at the moment :disappointed:
