### ISSUE TITLE
Give discount to users via RN , send discounted money in webview ? is it possible ?

### ISSUE THREAD

**Issue by Shikhar2404** [tcampb/react-calendly#161]
can i change the amount of money dynamically from webview to calendly? or is there any way i can send calculate price from my RN and send to calendly's event. i want to give discount to users

**Comment by tcampb** [comment]
Hi @Shikhar2404 -

The Calendly payment integrations (PayPal / Stripe) do not currently support applying discount codes. You would need to create multiple event types with varying prices for each discount and dynamically redirect the invitee to the correct event type.
