### ISSUE TITLE
How can I access the values I have selected?

### ISSUE THREAD

**Issue by artemyatsenko91** [tcampb/react-calendly#163]
Can I somehow get the date and time values that the user selected in PopupModal to additionally pass with my form for submission to the CRM?

Below I showed the code that I use

`import React from 'react'
import { useState } from 'react'
import { PopupModal } from 'react-calendly'
import style from './style.module.scss'

const CustomButtonExample = (props) => {
	const [isOpen, setState] = useState(false)

	return (
		<div>
			<button
				className={style.custom__button}
				onClick={() => setState(true)}
			>
				Custom Button
			</button>
			<PopupModal
				url={props.url}
				pageSettings={props.pageSettings}
				utm={props.utm}
				prefill={props.prefill}
				onModalClose={() => setState(false)}
				open={isOpen}
				rootElement={document.getElementById('__next')}
			/>
		</div>
	)
}

export default CustomButtonExample`

**Comment by siddiquiaffan** [comment]
You need to hit the calendly API with the data you got from PopupModal
