### ISSUE TITLE
[Feature] Support passing in a custom spinner component

### ISSUE THREAD

**Issue by ath88** [tcampb/react-calendly#164]
Hello,

~~I'd love to be able to show a spinner before the iframe has loaded, in case our user has a poor connection. This should be achievable by putting a spinner in front of the iframe, which I can hide once the iframe has loaded.~~

~~Please support a `onIframeLoaded`-event. I'm using the InlineWidget.~~

Thanks for awesome open source! :)

Edit: Turns out there is already a spinner, which is just hidden in my case, due to the z-index. Passing in a custom spinner component should make it possible to properly show the spinner in any case.

**Comment by tcampb** [comment]
Hey @ath88 - the default behavior of the `InlineWidget` should show a loading spinner; the screenshot below is what I see when I simulate a slow connection speed.

![image](https://github.com/tcampb/react-calendly/assets/33756113/7c1ab043-e9e5-4a0e-9770-00b62d91494d)

Is the loading spinner not appearing for you, or are you suggesting we add a feature to allow you to pass in your own loading spinner component?

**Comment by ath88** [comment]
The spinner is not loading for me, its just white. I guess that's my issue then. I'll check if we have some CSS that messes something up.

**Comment by ath88** [comment]
It turns out the `z-index: -1` puts the spinner too far back. It's hidden behind my page. Also, when using the InlineWidget, positioning it absolutely means it takes up the entire page, instead of the (probably small) window with the InlineWidget.

**Comment by tcampb** [comment]
Thanks for the additional info @ath88! If we added a way for you to pass in a custom loading spinner component would that solve the issue, or do you need access to the `onLoad` event directly?

**Comment by ath88** [comment]
Yes, a custom spinner should solve the problem as well. I'll change the issue.

**Comment by tcampb** [comment]
Great, thanks for confirming @ath88! I should have this change published later this week.

**Comment by ath88** [comment]
Sounds great! Thanks a lot!

**Comment by ath88** [comment]
Thanks! Much appreciated!
