### ISSUE TITLE
Too long time from hiding LoadingSpinner to showing Calendly widget

### ISSUE THREAD

**Issue by ath88** [tcampb/react-calendly#166]
Thanks for fixing that other issue! :)

I noticed that, depending on connection, there is time between hiding the loading spinner and drawing the calendly widget. 

While this is not a problem on decent connections, it can become confusing on poor connections, as nothing will be showing in-between.

[Screencast from 10-06-2023 01:58:18 PM.webm](https://github.com/tcampb/react-calendly/assets/167812/f76cd1c4-5c32-48a8-8bf0-9d636013b0ee)

Preferably, the spinner would be visible until the Calendly widget is fully ready to be drawn, or already loaded.

**Comment by tcampb** [comment]
Hey @ath88, I'm not aware of a way to detect when the content inside of the iframe is rendered; if you have an idea of how to implement this let me know and I can do some research.

As a workaround, you could use the [useCalendlyEventListener](https://github.com/tcampb/react-calendly#usecalendlyeventlistener) hook to detect when the profile / event type page is loaded.

**Comment by ath88** [comment]
Yea, after looking through the source it seems like there's nothing we can do outside of the `<iframe>`.

In my case, I can wait for the `onEventTypeViewed`-event before hiding my own spinner.

Thanks for doing this! :)
