### ISSUE TITLE
Getting an error of nested <div> - 

### ISSUE THREAD

**Issue by EladKarni** [tcampb/react-calendly#173]
I've run into an issue with the `<PopupButton />` component. It throws this errors anytime the iframe is displayed.
`validateDOMNesting(...): <div> cannot appear as a child of <html>`

![image](https://github.com/tcampb/react-calendly/assets/39969481/02a79c99-9ec0-4e71-9dbc-e7f5a31956df)

Any suggestions would be greatly appreciated!

**Comment by tcampb** [comment]
Hey @EladKarni - do you have a link to a public repo you could share where you were able to create this issue? 

Could you also try disabling all web extensions?

**Comment by EladKarni** [comment]
> Hey @EladKarni - do you have a link to a public repo you could share where you were able to create this issue?
> 
> Could you also try disabling all web extensions?

Thanks for getting back to me so quickly! I have tried it in `Incognito` mode so that shouldn't be the issue.

Let me get something up and running in Sandbox real quick and post it

**Comment by EladKarni** [comment]
> Hey @EladKarni - do you have a link to a public repo you could share where you were able to create this issue?
> 
> Could you also try disabling all web extensions?

I've managed to create a small test project to demonstrate the issue, but I can't reproduce it, so I'm spending some time with my existing project trying to figure it out. Apologies for the mess!
