### ISSUE TITLE
How to get meeting details on meeting confirmation?

### ISSUE THREAD

**Issue by Vivek377** [tcampb/react-calendly#177]
Hi, I want to access meeting details for example date and time after the meeting is scheduled by the user? I'm using useCalendlyEventListener but this doesn't provide meeting details.

`useCalendlyEventListener({
    onDateAndTimeSelected: (e) => {
      console.log(e.data.payload);
    },

    onEventScheduled: (e) => {
     console.log(e.data.payload);

    onEventTypeViewed: () => {
      setLoading(false);
    },
  });`

**Comment by tcampb** [comment]
@Vivek377 - unfortunately, the event payload does not provide any information about the meeting that was scheduled. To retrieve that info, you'd need to use Calendly's api:

https://developer.calendly.com/api-docs/e2f95ebd44914-get-event
