### ISSUE TITLE
<iframe> has permanent white background, despite the official examples are transparent

### ISSUE THREAD

**Issue by ArsenicBismuth** [tcampb/react-calendly#178]
Currently, you have permanent white background in your iframe. You can only change the panel's BG color (thanks to their API).

Meanwhile, the official examples are actually able to render a calendar with transparent iframe. See official example here: https://help.calendly.com/hc/en-us/articles/223147027-Embed-options-overview

Their pop-up iframe has transparent background, and it actually works nicely. But it's completely white in React. Below are some previews across the 3 different methods (pink to showcase the transparency).

![image](https://github.com/tcampb/react-calendly/assets/19264532/8001d8fd-3b8a-4221-b36f-d661147892ee)

![image](https://github.com/tcampb/react-calendly/assets/19264532/3cb43972-749b-4593-abf4-7b6eda369c07)

![image](https://github.com/tcampb/react-calendly/assets/19264532/b7a1e414-7a5a-4f6a-ba1d-894620c053a5)

Meanwhile this library is completely white. Which is kinda strange because the iframe here is similarly set to transparent in the inspect element.

![image](https://github.com/tcampb/react-calendly/assets/19264532/a3fd6e95-9089-433a-9821-8be6e49c8742)

**Comment by tcampb** [comment]
Hello,

Were you able to get this working using their embed code without React? If so, could you send the code that works and a link to your site with it working? That will allow me to understand what needs to be changed within the library.

**Comment by ArsenicBismuth** [comment]
@tcampb You mean in React, but as iframe? I haven't tried yet. So yea there's a possibility it's a React issue, and not the library's,

But a simple embedding in a simple page works perfect: https://codepen.io/ezeuz/pen/YzgXRYX

**Comment by tcampb** [comment]
A similar popup is working for me when using react-calendly, you can see the example here:

https://tcampb.github.io/react-calendly/?path=/story/components--popupwidget

Are you able to share the link to the specific page that is having this issue?

**Comment by ArsenicBismuth** [comment]
Oh wow you're right. So I played around with the theme/CSS thinking it might've caused the issue.

So turns out switching my CSS from the dark variant to the light variant fixed the issue for me (still using the same CSS framework):

![image](https://github.com/tcampb/react-calendly/assets/19264532/c517ccf9-bbbf-4cbb-9688-26db5fb6deb3)

So I stumble this before while searching around, and it might be because the meta tag of the iframe (which is light), is conflicting with the meta tag of my website (which is dark).

I might be able to find a solution later on, will keep this issue open until then.

**Comment by ArsenicBismuth** [comment]
Ok found the specified issue: https://stackoverflow.com/a/77604431

> If the color scheme of an iframe differs from embedding document, iframe gets an opaque canvas background appropriate to its color scheme.

**Comment by tcampb** [comment]
Wow, great find! I didn't even know about the `color-scheme` meta tag :sweat_smile:

**Comment by ArsenicBismuth** [comment]
Ok solved it! For you guys, all you need to do is just to add `colorScheme: "white"` in your Calendly component's style!

Example:

 ```
<InlineWidget 
  styles={{colorScheme: "white"}}
  pageSettings={pageSettings}
  url="https://calendly.com/embed-demo-customer-success/q-a-session" />
 ```

All in all this will make the iframe thinks you're on the same color scheme, thus will not render/add white canvas as a background.

**Comment by JacobMuchow** [comment]
Wow, thank you. This was such a pain!
