### ISSUE TITLE
Render error

### ISSUE THREAD

**Issue by sajeeIfonix** [tcampb/react-calendly#180]
I am trying to integrate the Calendly iframe with a react-native app.

I have installed the Node package: https://www.npmjs.com/package/react-calendly

I want to use the InlineWidget component. So, I wrote a component for it, substituting div with View.
![react native calendly](https://github.com/tcampb/react-calendly/assets/135217672/a11a98af-bd80-4a35-8519-bd0a20c78bf9)

<img width="233" alt="Screenshot 2024-02-21 103211" src="https://github.com/tcampb/react-calendly/assets/135217672/9488ff43-d035-457b-8b4d-0698df76c1c3">
<img width="233" alt="Screenshot 2024-02-21 103231" src="https://github.com/tcampb/react-calendly/assets/135217672/1fc9691f-d04f-4d12-aba6-b26eba505f5f">

**Comment by tcampb** [comment]
Hi @sajeeIfonix,

The `react-calendly` components do not currently support react native applications. However, you may be able to use a WebView with Calendly's embed code as seen in the code example here:

https://github.com/tcampb/react-calendly/issues/142
