### ISSUE TITLE
is it possible to make the popup button responsive ?

### ISSUE THREAD

**Issue by magmukendi** [tcampb/react-calendly#182]
I am currently working on applying the popup button on one of my work projects, but it seems like it's quite hard to make it responsive. Unless it depends to another parent div.

let say I want to set it width to 15vw on desktop and 90% on mobile, I would not be able to create different width for different screensize as it is done in material UI `width:{xs:'90%', md:'15vw}` 

I would need put it in a parent div that will be responsive then the button becomes responsive too if it's width is set to 100%.

Would it be possible to work on customizing the style so that it is responsive independently to other parent element ? I can work on this one if possible. 

I am open to providing more details if needed.

**Comment by tcampb** [comment]
Hey @magmukendi - 

The `PopupButton` implementation is currently just a copy of Calendly's existing embed code css:
https://github.com/tcampb/react-calendly/blob/master/src/calendly-widget.css

To create a more responsive version I would recommend using the `PopupModal` component to create a custom button:
https://github.com/tcampb/react-calendly?tab=readme-ov-file#how-do-i-create-a-custom-button-that-triggers-a-pop-up-scheduler
