### ISSUE TITLE
New(?) url param: `data-resize="true"`

### ISSUE THREAD

**Issue by k-funk** [tcampb/react-calendly#187]
Could you add `data-resize="true"` to the next release? I'm not sure if it's new, or was intentionally left out. Guessing the former.

[Docs here](https://help.calendly.com/hc/en-us/articles/223147027-Embed-options-overview?tab=advanced#h_01HZHZV25M0VT4YDB0RKBX40S4).

**Comment by tcampb** [comment]
Hi @k-funk -

Version 4.3.1 updates the  `useCalendlyEventListener` hook to include an `onPageHeightResize` option.

This allows you to resize the parent container when the Calendly scheduling page's height changes. 

For example:

```jsx
import {
  InlineWidget,
  useCalendlyEventListener,
} from "react-calendly";

function App() {
  const [height, setHeight] = useState('500px');
  const onPageHeightResize = (e) => setHeight(e.data.payload.height);

  useCalendlyEventListener({
    onPageHeightResize
  })

  return (
    <>
      <InlineWidget
        styles={{ height }}
        url="https://calendly.com/acmesales"
      />
    </>
  );
}
```

**Comment by mikaelgramont** [comment]
Hey all, I posted the quick PR above, hoping to add the attribute that @k-funk mentioned, and that I find myself missing as well.

**Comment by tcampb** [comment]
Hey @mikaelgramont @k-funk - 

The data resize attribute is only used by Calendly's embed script, which can be found here (https://assets.calendly.com/assets/external/widget.js). As a result, adding the attribute to the iframe in this library won't automatically resize it unless you load in the linked file. This library is not meant to be a 1 to 1 match of Calendly's embed script.

**Comment by mikaelgramont** [comment]
Ah, I see, I had glossed over that important detail.
