### ISSUE TITLE
Extra vertical scroll bar 

### ISSUE THREAD

**Issue by codal-umistri** [tcampb/react-calendly#189]
**Do you know how to get rid of the extra scrolling that appears?**

 **Code:-**
```
import React, { useEffect } from 'react';
import { InlineWidget } from 'react-calendly';

interface ScheduleMeeting {
  url: string;
}

const ScheduleMeeting: React.FC<ScheduleMeeting> = ({ url }) => {
  return (
    <div className="mt-0 mb-0">
      <InlineWidget
        url={url}
        styles={{
          overflow: 'hidden',
          marginTop:'0px'
          
        }}
      />
    </div>
  );
};

export default ScheduleMeeting;
```

**Attachment:-** 
![image](https://github.com/user-attachments/assets/e6091700-0fa0-44a2-af53-1a49533bfeed)

I think that is coming due to applied margin
![calendy issue](https://github.com/user-attachments/assets/8f0ec851-9fce-4537-b692-5da830d386b2)

**Comment by tcampb** [comment]
Hey @codal-umistri -

The scrollbar appears when the iframe content's height exceeds the height of the parent container. You can use the `onPageHeightResize` option in the `useCalendlyEventListener` hook to dynamically adjust the height of the container.

For example:

```jsx
import {
  InlineWidget,
  useCalendlyEventListener,
} from "react-calendly";

function App() {
  const [height, setHeight] = useState('500px');
  const onPageHeightResize = (e) => setHeight(e.data.payload.height);

  useCalendlyEventListener({
    onPageHeightResize
  })

  return (
    <>
      <InlineWidget
        styles={{ height }}
        url="https://calendly.com/acmesales"
      />
    </>
  );
}
```

**Comment by codal-umistri** [comment]
Thank you, @tcampb! Can we use useCalendlyEventListener to dynamically remove elements, such as the anchor link in the top-right corner?

**Comment by tcampb** [comment]
The "Powered By Calendly" link can be removed in your Calendly account setting's page:

[https://calendly.com/app/personal/branding](https://calendly.com/app/personal/branding)

**Comment by codal-umistri** [comment]
Thanks @tcampb!
