### ISSUE TITLE
Infinitely Loading Widget

### ISSUE THREAD

**Issue by Rterrell25** [tcampb/react-calendly#20]
Currently using the react-calendly package and have implemented it into my react-application like so:

```
import React, { useState } from 'react'
import { InlineWidget } from 'react-calendly'

function App() {
  return (
    <>
      <InlineWidget
        url='https://calendly.com/robert-612/complimentary-consultation'
        utm={{
          utmCampaign: 'Spring Sale 2019',
          utmContent: 'Shoe and Shirts',
          utmMedium: 'Ad',
          utmSource: 'Facebook',
          utmTerm: 'Spring'
        }}
      />
    </>
  )
}

export default App
```

The widget is working as expected, I am able to schedule, etc.  the only issue is there are three dots indicating the widget is in a loading state and they never go away.  It looks like the following:
![Screen Shot 2020-09-09 at 1 09 38 PM](https://user-images.githubusercontent.com/54453743/92630614-1a680280-f29e-11ea-8f41-d5273a73cea1.png)

When checking the console I get the following issue from the Chrome Dev Tools:

Resolve this issue by updating the attributes of the cookie:
Specify SameSite=None and Secure if the cookie is intended to be set in cross-site contexts. Note that only cookies sent over HTTPS may use the Secure attribute.
Specify SameSite=Strict or SameSite=Lax if the cookie should not be set by cross-site requests

is there something I'm missing?

**Comment by tcampb** [comment]
Thanks for finding this @Rterrell25! This should be fixed now (see https://github.com/tcampb/react-calendly/pull/24/files). 

@marshallhahn updated the `react-calendly` package to hide the loading animation once the iframe has been loaded.
