### ISSUE TITLE
how to get the selected date,time and event type of calendly event callback.

### ISSUE THREAD

**Issue by sai5yinc** [tcampb/react-calendly#22]
How to get the selected date, time, and event type of calendly event callback.

**Comment by tcampb** [comment]
Unfortunately, this data is not currently available as a callback parameter. The message sent to the parent window only contains the event name at this time - https://help.calendly.com/hc/en-us/articles/360020052833-Advanced-embed-options#3

However, Calendly supports webhooks which allow you to receive Calendly appointment data in real-time at a specified URL when a Calendly event is scheduled or cancelled. [This data includes the event date, time, and event type](https://developer.calendly.com/docs/sample-webhook-data).

https://developer.calendly.com/docs/webhook-subscriptions

**Comment by sai5yinc** [comment]
Thanks @tcampb
