### ISSUE TITLE
InlineWidget is duplicated

### ISSUE THREAD

**Issue by nomadus** [tcampb/react-calendly#25]
I am trying to embed Calendly on my site, I have added the following code 
```
<InlineWidget
          url="https://calendly.com/my_username/60min?month=2020-09"/>
```
And I get three copies of Calendly. All the copies show 60 min time slot and September as a month, they all the same.

**Comment by tcampb** [comment]
I wasn't able to recreate this issue using the code above. Do you have a public repository that you could share where you were able to recreate this issue?

**Comment by brettmfox33** [comment]
I was also having this issue yesterday. It fixed itself though once I moved the InlineWidget to its own component rather than rendering it to its parent component.

**Comment by tcampb** [comment]
@brettmfox33 - do you happen to have a public repository that you could share where you were able to recreate this issue? I would love to look into this issue further if possible.

**Comment by jordie23** [comment]
@tcampb 

This will result in 2 widgets being displayed:

```javascript
import { useState, useEffect } from 'react'
import { InlineWidget } from 'react-calendly'

export default function Home() {
  const [value, setValue] = useState(0)

  useEffect(() => {
    // i'm doing something with window.innerWidth here but for the sake of simplicity this causes it too
    setValue(1)
  }, [])

  return (
    <div>
      My value: {value}
      <InlineWidget
        url="your-calenderly-event-url?primary_color=ff2100&hide_event_type_details=1"
        prefill={{
          email: 'test@example.com',
          name: 'Jon Snow',
        }}
      />
    </div>
  )
}
```

For me it happens when the component the widget is in has a useEffect that then calls a setState causing a re-render and then there'll be two widgets displayed. 

Note: I'm also using next.js, so this is using SSR then client side hydration then the useEffect runs.

I was planning to extract things out to different components anyway so I moved the InlineWidget to another component that is memoized and the problem doesn't happen anymore.

**Comment by jordie23** [comment]
Actually, I'm mistaken. Putting it into a memoized component does NOT stop the issue occurring it seems. It worked due to the hot-reload in next.js, but if do a proper page reload it'll have 2 widgets.

**Comment by tcampb** [comment]
Thanks @jordie23 for the detailed explanation! I was only able to re-create the issue when using Google Chrome; this bug did not occur when using Safari or Firefox. 

I created a [PR](https://github.com/tcampb/react-calendly/pull/30) to fix this issue and should have it merged soon. It seems like on Chrome specifically `destroyInlineWidget` (method that removes the previously rendered widget) executes _before_ the iframe is inserted into the DOM via componentDidMount. The PR referenced above uses `MutationObserver` to wait for the iframe to be inserted before calling `destroyInlineWidget`.
