### ISSUE TITLE
X-Frame-Options Error

### ISSUE THREAD

**Issue by brettmfox33** [tcampb/react-calendly#26]
I am getting an X-Frame-Options error when using the **InlineWidget** component. It seems to be a setting that the library sets not my server. The widget still works and it connects to my calendar correctly but I am getting this error in the console.

The following is the error: 
`Invalid X-Frame-Options header was found when loading "https://calendly.com/<username>/15min?embed_domain=big-bud-bookkeeping.web.app&embed_type=Inline&primary_color=60258d”: “ALLOWALL” is not a valid directive.`

The following is my code:
`<InlineWidget 
        styles={{
            height: '1000px'
        }}
        pageSettings={{
            primaryColor: "60258d"
        }}
        url="https://calendly.com/<username>/15min"
    />`

<img width="1792" alt="Screen Shot 2020-09-27 at 3 42 21 PM" src="https://user-images.githubusercontent.com/65796019/94374114-13335800-00d8-11eb-82a4-44d94705317f.png">

**Comment by tcampb** [comment]
Unfortunately, we cannot prevent this error from occurring within the `react-calendly` library since this header is sent from Calendly's server when the iframe is loaded.
