### ISSUE TITLE
InlineWidget is re-fetched every time the parent component is re-rendered

### ISSUE THREAD

**Issue by m-weeks** [tcampb/react-calendly#27]
Every time the parent component is re-rendered, the inline widget gets reloaded.

See the following example:

https://codesandbox.io/s/tender-matsumoto-fh61h?file=/src/App.js

When typing in the input above the widget, the widget gets reloaded.

**Comment by tcampb** [comment]
Just merged your PR, thanks again for finding and fixing this issue @m-weeks!
