### ISSUE TITLE
Lack of clarity in your readme

### ISSUE THREAD

**Issue by heysoypaez** [tcampb/react-calendly#3]
I think it package would be better if you **put in your readme snippet of code implementing it.**

I had to look inside the repository to know the real name of the component.

Because `<Inline />` was not one. For example.

**Comment by tcampb** [comment]
Thanks for catching this! I've updated the documentation to use storybook to ensure that the documentation matches the code. 

https://tcampb.github.io/react-calendly

You can click on `Show Info` in the top right corner of the window to view the code implementation.

**Comment by heysoypaez** [comment]
Great, it is a lot better!!!
