### ISSUE TITLE
Breaks Aos?

### ISSUE THREAD

**Issue by alvisanovari** [tcampb/react-calendly#35]
Hi - great job on this. This is random but for some reason this breaks Animation on Scroll. If I load an InlineWidget on one page and toggle between that and a page that uses the Aos library it hides/doesn't render all my elements that were being animated on that page. Any idea what this is?

**Comment by tcampb** [comment]
@alvisanovari - do you happen to have a public repository that you could share where you were able to recreate this issue? I would love to look into this issue further if possible.
