### ISSUE TITLE
Missing location prefill

### ISSUE THREAD

**Issue by otherjohn** [tcampb/react-calendly#38]
Hi,
According to [this calendly support post](https://help.calendly.com/hc/en-us/community/posts/360009519493/comments/360011494973)
In order to prefill the phone field on some forms, you need to use the **'location'** (not 'phone')

Can this be added to the code?

**Comment by tcampb** [comment]
Thanks for finding this @otherjohn! I just published version `1.2.0` which adds `location` to the `prefill` options.
