### ISSUE TITLE
hook for tracking events

### ISSUE THREAD

**Issue by jeetiss** [tcampb/react-calendly#45]
`CalendlyEventListener` can be replaced with similar hook `useCalendlyEvents`, and it can be useful

**Comment by Memogcia** [comment]
Maybe also find a way to differentiate between callers, like passing a custom Id or value to the Calendly component in order to distinguish the source, for example:  a group of buttons that opens the widget of Calendly.

**Comment by tcampb** [comment]
@jeetiss - `CalendlyEventListener` has been replaced by `useCalendlyEventListener` in version `4.0.0`.

@Memogcia - now that the component has been converted to a hook I plan on looking into adding an option to scope the event listener to a specific scheduling widget. 

Example:

```tsx
<InlineWidget onDateAndTimeSelected={() => console.log('inline widget')} />
<PopupWidget onDateAndTimeSelected={() => console.log('popup widget')} />
```

The example above would allow you to determine which scheduling widget was used to select a date / time.

**Comment by blessingonuoha** [comment]
Can we grab the value of the selected date and time using the onDateAndTimeSelected handler ?

**Comment by tcampb** [comment]
Hi @blessingonuoha, 

Unfortunately, [Calendly's embed api](https://developer.calendly.com/api-docs/ZG9jOjI3ODM2MTAz-notifying-the-parent-window) does not send the selected date time data. 

To retrieve this data, you'd need to use a tool like [cloakist](https://cloak.ist/?ref=calforce) to host the Calendly scheduling page **without** using an iframe. This would allow you to attach a javascript event listener to the scheduling page directly. An example video of what this looks like can be found [here](https://youtu.be/jZlSy06L_UM).
