### ISSUE TITLE
Calendly reloads when trying to input on android chrome browser

### ISSUE THREAD

**Issue by sipotat** [tcampb/react-calendly#46]
Hey
I'm using InlineWidget and when opening the page in a chrome browser on android, whenever the user try to press any of the input fields (name, email, phone, etc) the widget is being reloaded automatically.

Thanks for your help

**Comment by tcampb** [comment]
Hi @sipotat, 

Do you happen to have a public repository that you could share where you were able to recreate this issue? I tried viewing the inline widget in the storybook documentation using an android device and was unable to recreate the issue.

**Comment by sipotat** [comment]
So apparently clicking on a text input in the calendly iframe inside android chrome browser triggers the onresize event, which I was using and which results in refreshing the page.

**Comment by bundit** [comment]
My PR #67 likely addresses this issue
