### ISSUE TITLE
Add possibility to add custom attribute to resulting iframe for Hotjar Tracking

### ISSUE THREAD

**Issue by Perni1984** [tcampb/react-calendly#48]
## Description
We would like to use hotjar to track movement on an embedded calendly iframe.

Hotjar has several privacy enhancements to only track activity in certain whitelisted iframes. To whitelist an iframe you have besides whitelisting the domain in the hotjar site settings also add an additional attribute `data-hj-allow-iframe` to the rendered iframe.

## Expected Behavior
The calendly iframe is rendered including a `data-hj-allow-iframe` attribute:

```
<iframe data-hj-allow-iframe src="https://calendly.com/..." width="100%" height="100%" frameborder="0"></iframe>
```

## Actual Behavior
It is not possible to add a custom attribute to the calendly iframe due to restrictions in the typings.

**Comment by tcampb** [comment]
Hi @Perni1984 -

Does using the `iframe` tag work as expected without using `react-calendly`?

```html
<iframe data-hj-allow-iframe src="https://calendly.com/..." width="100%" height="100%" frameborder="0"></iframe>
```

According to their [documentation](https://help.hotjar.com/hc/en-us/articles/115011624347-Can-I-track-iframes-inside-Recordings-#adding-an-html-attribute-to-the-iframe) the `data-hj-allow-iframe` cannot be added to third-party iframes.

> If your iframe is **not a third-party** iframe and is hosted on your site, you can add an HTML attribute to make viewing the content within your Recordings possible. Movement and input data will still not be captured.
