### ISSUE TITLE
Install error on npm

### ISSUE THREAD

**Issue by kinglycodes** [tcampb/react-calendly#51]
I get an install error with npm.

`❯ npm install --save react-calendly
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: xxx@0.1.0
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^15.0.0 || ^16.0.0" from react-calendly@1.3.0
npm ERR! node_modules/react-calendly
npm ERR!   react-calendly@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.`

Could you please help me?

**Comment by tcampb** [comment]
Thanks for letting me know about this error @kinglycodes!

It looks like [npm version 7](https://github.blog/2021-02-02-npm-7-is-now-generally-available/#peer-dependencies) will block installations if an upstream dependency conflict is present that cannot be automatically resolved. Currently, the react-calendly [package.json](https://github.com/tcampb/react-calendly/blob/master/package.json#L34) does not list `react@17.0.1` as a peer dependency which would explain why the error is occurring. 

I'll test `react-calendly` with `react@17.0.1` and if everything works I can update the peer dependencies. In the meantime, you can run `npm install --save --legacy-peer-deps react-calendly` to install this package with npm version 7.

**Comment by kinglycodes** [comment]
Thank you for the super fast reply and the testing. :)
I will try with the legacy peer deps.

**Comment by kinglycodes** [comment]
It worked with the legacy peer deps.
