### ISSUE TITLE
hideLandingPageDetails not working

### ISSUE THREAD

**Issue by empz** [tcampb/react-calendly#55]
Setting `hideLandingPageDetails` to `true` doesn't seem to work. Looks the same as setting it to `false.

```js
<PopupText
  url="mycalendlyeventurl"
  text="Schedule Here"
  pageSettings={{
    hideLandingPageDetails: true,
  }}
/>
```

Unless this is a Pro feature only?

**Comment by tcampb** [comment]
Hi @empz,

This feature is available on the free, premium, and pro plans. The `hideLandingPageDetails` attribute only applies to team pages and your personal Calendly landing page. For example, `hideLandingPageDetails` would work when the url is https://calendly.com/acmesales but not work when the url references a specific event type such as https://calendly.com/acmesales/pricing-review.

To hide the page details for a specific event type you can use the `hideEventTypeDetails` property.

**Comment by empz** [comment]
Thanks for the quick reply. I was indeed using an event URL.
