### ISSUE TITLE
Pre-populate additional guests

### ISSUE THREAD

**Issue by nandosangenetto** [tcampb/react-calendly#64]
Does it currently supports a way to prefill additional guests? 

https://help.calendly.com/hc/en-us/articles/226766767-Pre-populate-invitee-information-on-the-scheduling-page

If not, could you please guide me to a good starting point to add this to this lib?

**Comment by nandosangenetto** [comment]
I've created a PR #65 to solve this issue. Let me know if I need to change anything.

**Comment by tcampb** [comment]
Thanks @nandosangenetto!

I just merged https://github.com/tcampb/react-calendly/pull/65 and published the latest version to npm.
