### ISSUE TITLE
Sometimes it doesn't load

### ISSUE THREAD

**Issue by olegKusov** [tcampb/react-calendly#69]
When I open popup with calendly inline widget very often it doesn't load. I don't know why.

**Comment by kevinreber** [comment]
@olegKusov Have you checked if the styling is being applied? I've noticed `calendly-widget.css` isn't being injected when using the `openPopupWidget` and `PopupButton` component.

**Comment by tcampb** [comment]
@olegKusov @kevinreber - Thanks for creating this Github issue; it looks like setting the postcss `modules` option to true was causing the issue - see [here](https://github.com/tcampb/react-calendly/commit/5c0b45606fe7e8e25a02183e8e3755c55f6ddffc#diff-6814bf77564b4f1c92f5861e184e28fe217c080a047fefa8b73a728f755ec45cL25). I just published a new version [(2.0.4)](https://www.npmjs.com/package/react-calendly) which should fix this.

**Comment by olegKusov** [comment]
> @olegKusov @kevinreber - Thanks for creating this Github issue; it looks like setting the postcss `modules` option to true was causing the issue - see [here](https://github.com/tcampb/react-calendly/commit/5c0b45606fe7e8e25a02183e8e3755c55f6ddffc#diff-6814bf77564b4f1c92f5861e184e28fe217c080a047fefa8b73a728f755ec45cL25). I just published a new version [(2.0.4)](https://www.npmjs.com/package/react-calendly) which should fix this.

thanks for the quick feedback!!
