### ISSUE TITLE
Is there any way to get the invitee info from onEventScheduled event object?

### ISSUE THREAD

**Issue by bundit** [tcampb/react-calendly#72]
Or is there any way to get the invitee info after an event is scheduled?

**Comment by tcampb** [comment]
Hi @bundit,

You can send a request to the invitee uri included in the [`onEventScheduled`](https://github.com/tcampb/react-calendly#how-can-i-access-the-event-details-when-an-event-is-scheduled) payload object to retrieve the invitee information (see [here](https://calendly.stoplight.io/docs/api-docs/reference/calendly-api/openapi.yaml/paths/~1scheduled_events~1%7Bevent_uuid%7D~1invitees~1%7Binvitee_uuid%7D/get))

```javascript
{
  event: "calendly.event_scheduled",
  payload: {
    event: {
      uri: "https://calendly.com/api/v2/scheduled_events/AAAAAAAAAAAAAA"
    },
    invitee: {
      uri: "https://calendly.com/api/v2/scheduled_events/AAAAAAAAAAAAAA/invitees/AAAAAAAAAAAAAA"
    }
  }
}
```

**Comment by doublejosh** [comment]
That's not really useful since this embed exists on the front-end and you need an access token.

So the answer is really that you can't.
