### ISSUE TITLE
TypeScript error when importing

### ISSUE THREAD

**Issue by ethankeshishian** [tcampb/react-calendly#79]
This is the error given:
```
D:/.../node_modules/react-calendly/typings/index.d.ts
TypeScript error in D:/.../node_modules/react-calendly/typings/index.d.ts(5,13):
'=' expected.  TS1005

    3 | import PopupWidget from "./components/PopupWidget/PopupWidget";
    4 | import CalendlyEventListener from "./components/CalendlyEventListener/CalendlyEventListener";
  > 5 | import type { DateAndTimeSelectedEvent, EventScheduledEvent, EventTypeViewedEvent, ProfilePageViewedEvent } from "./components/CalendlyEventListener/CalendlyEventListener";
      |             ^
    6 | import { openPopupWidget, closePopupWidget } from './calendly';
    7 | export { InlineWidget };
    8 | export { PopupButton };
```

**Comment by tcampb** [comment]
@ethankeshishian - what version of typescript are you currently using?

**Comment by ethankeshishian** [comment]
I'm running version 3.7.2.

**Comment by tcampb** [comment]
It looks like the `import type` feature requires typescript version 3.8 or greater - https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html

Would it be possible for you to upgrade to 3.8 or would this cause too many breaking changes?

**Comment by ethankeshishian** [comment]
Updated to 3.8 by updating `package.json`, no breaking changes thus far. Thanks.

Also, one workaround that seemed to work was deleting the line in `node_modules`.
