### ISSUE TITLE
add screenshots to the readme

### ISSUE THREAD

**Issue by noob-master147** [tcampb/react-calendly#80]
@tcampb 
Since it is a Frontend tool, it would be great and very very useful if you can add a few screen-shots of the rendered calendar.
It will help the developers quickly understand the capabilities of the package.

**Comment by tcampb** [comment]
Hi Divyansh,

Thanks for your feedback! Would it be helpful to make the storybook link more prominent on the README, or are you suggesting that we add screenshots to the README along with the storybook link? My hope was that developers interested in using the library would visit the storybook link to view / demo the components - https://tcampb.github.io/react-calendly/?path=/story/components--inlinewidget

**Comment by noob-master147** [comment]
I'd say add screenshots to the readme itself. This would also reflect on
the npm package page and will help developer to quickly what the package is
capable of.

Best Regards
Divyansh
