### ISSUE TITLE
Background color not working with InlineWidget

### ISSUE THREAD

**Issue by seawatts** [tcampb/react-calendly#86]
When trying to change the `backgroundColor` param in the `pageSettings` argument, it does not actually change the background color.

I'm not sure if Calendly changed their API? Also, it looks like your imported `external/widget.js` looks to be outdated. Is there a reason you are pulling that in manually instead of just always calling theirs dynamically?

**Comment by seawatts** [comment]
Never mind I got it working. However, apparently, it does not work with anything other than hex codes.

**Comment by aldaw** [comment]
Could you explain how you have solved it exactly?
