### ISSUE TITLE
Please create a Changelog

### ISSUE THREAD

**Issue by steelbrain** [tcampb/react-calendly#90]
Hi @tcampb 

Thank you so much for working on this package! We have been using it for a while and love it.
Right now, whenever we try to upgrade between versions, we have to dig through the Github commits to figure out what was changed and how to proceed with the upgrade.

Could you please publish a Changelog (and optionally post release notes on the releases themselves)?

Thank you!

**Comment by tcampb** [comment]
Thanks for the suggestion @steelbrain! I've added a changelog document [here](https://github.com/tcampb/react-calendly/blob/master/CHANGELOG.md); it currently only contains information about the latest release, but I will be sure to update this document (and the release notes) for future releases.
