### ISSUE TITLE
it is possible to obtain the date and time chosen by the user

### ISSUE THREAD

**Issue by jdaniel-ap** [tcampb/react-calendly#92]
Hello, everybody.

I was wondering if it is possible to obtain the date and time chosen by the user with the event onDateAndTimeSelected. I've been testing and it always generates an empty payload key.

`Calendly Event: {"event":"calendly.date_and_time_selected","payload":{}}`

**Comment by tcampb** [comment]
Unfortunately, this data is not currently available as a callback parameter. The message sent to the parent window only contains the event name at this time - https://calendly.stoplight.io/docs/embed-api-docs/ZG9jOjI2NzAyMzk-notifying-the-parent-window

**Comment by jdaniel-ap** [comment]
> Unfortunately, this data is not currently available as a callback parameter. The message sent to the parent window only contains the event name at this time - https://calendly.stoplight.io/docs/embed-api-docs/ZG9jOjI2NzAyMzk-notifying-the-parent-window

Thank you very much, I thought the information could be obtained before sending it to Calendly. But I will have to fetch the endpoints that `"calendly.event_scheduled" `throws
