### ISSUE TITLE
Use without an iframe?

### ISSUE THREAD

**Issue by jordanlambrecht** [tcampb/react-calendly#94]
Does Calendly's API allow you to use the fullpage widget without an iframe? I hate iFrames =[

**Comment by tcampb** [comment]
@jordanlambrecht  - Unfortunately, [Calendly's api](https://calendly.stoplight.io/docs/api-docs/ZG9jOjE4MTk2MTg-api-conventions) does not currently provide an endpoint to retrieve an event's availability or schedule an event.
