### ISSUE TITLE
Allow setting a custom iframe title

### ISSUE THREAD

**Issue by RiinaVi** [tcampb/react-calendly#96]
https://web.dev/frame-title/?utm_source=lighthouse&utm_medium=devtools

**Comment by tcampb** [comment]
Thanks for creating this github issue @RiinaVi! The `iframeTitle` prop is now available in version 2.2.3 - https://github.com/tcampb/react-calendly/pull/97

If the iframeTitle prop is not provided then the iframe will use "Calendly Scheduling Page" as the default title.
